CREATE OR REPLACE CORTEX SEARCH SERVICE "STOCK_NEWS_SEARCH_SERVICE"
ON "SEARCH_TEXT"
ATTRIBUTES "HEADLINE", "STOCK", "DATE", "SENTIMENT"
WAREHOUSE = "DOD_WAREHOUSE"
TARGET_LAG = '30 days'
AS
SELECT
    "HEADLINE",
    "STOCK", 
    "DATE",
    "SENTIMENT",
    "PUBLISHER",
    ('Headline\n\n' || "HEADLINE" || '\n\nPublisher\n\n' || "PUBLISHER" ... || '\n\n\On Date: \n\n' || TO_VARCHAR("DATE")) as "SEARCH_TEXT"
FROM STOCK_NEWS_EVENT;