-- Pipe loads CSV files from stage into the landing table
CREATE OR REPLACE PIPE "STOCK_NEWS_PIPE" AUTO_INGEST = FALSE AS
  COPY INTO "STOCK_NEWS_RAW"
  FROM @"STOCK_NEWS_STAGE"
  FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);