CREATE ROLE IF NOT EXISTS DOD_DATA_ANALYST;

GRANT USAGE ON DATABASE MY_DATABASE
TO ROLE DOD_DATA_ANALYST;

GRANT USAGE ON SCHEMA MY_DATABASE.MY_SCHEMA
TO ROLE DOD_DATA_ANALYST;

GRANT SELECT ON TABLE MY_DATABASE.MY_SCHEMA.IMPORTANT_DATA
TO ROLE DOD_DATA_ANALYST;

GRANT ROLE DOD_DATA_ANALYST
TO USER JOHN_DOE;

GRANT USAGE ON WAREHOUSE MY_WAREHOUSE
TO ROLE DOD_DATA_ANALYST;