-- Create a share object
CREATE OR REPLACE SHARE "STOCK_SHARE";

-- Grant share object permissions to database objects
GRANT USAGE ON DATABASE "DOD2026" TO SHARE "STOCK_SHARE";
GRANT USAGE ON SCHEMA "DOD2026"."PUBLIC" TO SHARE "STOCK_SHARE";
GRANT SELECT ON TABLE "DOD2026"."PUBLIC"."DAILY_STOCK_PRICES" TO SHARE "STOCK_SHARE";

-- Grant snowflake accounts access to share
ALTER SHARE "STOCK_SHARE" ADD ACCOUNTS=BNLFPXH.WP41299;