CREATE TASK MY_TASK
  SCHEDULE = 'USING CRON 30 * * * * UTC'
  TIMESTAMP_INPUT_FORMAT = 'YYYY-MM-DD HH24'
  WAREHOUSE = 'DOD_WAREHOUSE'
  AS
    INSERT INTO MY_TIMESTAMP_TABLE(ts) VALUES(CURRENT_TIMESTAMP);