ALTER USER IF EXISTS "DOD_USER" ADD PROGRAMMATIC ACCESS TOKEN "DEV_ACCESS_TOKEN"
  DAYS_TO_EXPIRY = 30,
  ROLE_RESTRICTION = 'DOD_DEVELOPER'
  COMMENT = 'A developer token that expires after a month';