-- List what we already have
SHOW WAREHOUSES;
SHOW ROLES;
SHOW USERS;

CREATE DATABASE IF NOT EXISTS "DOD2026";

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS "DOD_WAREHOUSE" WITH 
    WAREHOUSE_TYPE = 'STANDARD'
    WAREHOUSE_SIZE = 'X-SMALL'
    MAX_CLUSTER_COUNT = 1
    AUTO_SUSPEND = 60
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'This is my fancy new data warehouse for the DOD2026 in Graz!';

-- Role
CREATE ROLE IF NOT EXISTS "DOD_DEVELOPER"
  COMMENT = 'An example rol for development in the DOD2026 workshop';

-- (Optional) Apply the role to the its place in the hierachy
GRANT ROLE "DOD_DEVELOPER" TO ROLE SYSADMIN;

-- Permissions
GRANT ALL PRIVILEGES ON WAREHOUSE "DOD_WAREHOUSE" TO ROLE "DOD_DEVELOPER";
GRANT EXECUTE TASK ON ACCOUNT TO ROLE "DOD_DEVELOPER";

-- GRANT OWNERSHIP ON DATABASE "DOD2026" TO ROLE "DOD_DEVELOPER";
GRANT ALL PRIVILEGES ON DATABASE "DOD2026" TO ROLE "DOD_DEVELOPER";
GRANT ALL PRIVILEGES ON SCHEMA "DOD2026"."PUBLIC" TO ROLE "DOD_DEVELOPER";

-- User
CREATE USER "DOD_USER" PASSWORD='<your-secure-pw>' DEFAULT_ROLE = "DOD_DEVELOPER";
GRANT ROLE "DOD_DEVELOPER" TO USER "DOD_USER";

SHOW GRANTS TO USER "DOD_USER";

-- User can now successfully sign into SnowSight but will be prompted for MFA
-- Programatic access tokens can be used instead of a password
ALTER USER IF EXISTS "DOD_USER" ADD PROGRAMMATIC ACCESS TOKEN "DEV_ACCESS_TOKEN"
  DAYS_TO_EXPIRY = 30
  ROLE_RESTRICTION = 'DOD_DEVELOPER'
  COMMENT = 'A developer token that expires after a month';

-- Cleanup access
-- ALTER USER "DOD_USER" REMOVE PROGRAMMATIC ACCESS TOKEN "DEV_ACCESS_TOKEN";

-- Display any PAT Tokens
SHOW USER PROGRAMMATIC ACCESS TOKENS FOR USER "DOD_USER";

-- Network Policies
CREATE OR REPLACE NETWORK POLICY "DOD_NETWORK_POLICY"
    -- Allows all IPs; restrict in production
    ALLOWED_IP_LIST = ('0.0.0.0/0')  
    COMMENT = 'Policy for programmatic access on DevOpsDays';

ALTER USER "DOD_USER" SET NETWORK_POLICY = 'DOD_NETWORK_POLICY';
-- ALTER ACCOUNT SET NETWORK_POLICY = 'DOD_NETWORK_POLICY';

SHOW NETWORK POLICIES;