USE ROLE "DOD_DEVELOPER";
USE DATABASE "DOD2026";
USE SCHEMA "PUBLIC";

-- Create a stage for incoming stock news files (comma-separated with header)
CREATE OR REPLACE STAGE "STOCK_NEWS_STAGE"
  FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);

-- Landing table for the pipe (raw ingest, matches CSV column order)
CREATE OR REPLACE TABLE "STOCK_NEWS_RAW" (
  ID         NUMBER,
  HEADLINE   STRING,
  URL        STRING,
  PUBLISHER  STRING,
  DATE       TIMESTAMP,
  STOCK      STRING
);

-- Final target table with AI sentiment label and embedding
CREATE OR REPLACE TABLE "STOCK_NEWS_EVENT" (
  HEADLINE   STRING,
  PUBLISHER  STRING,
  DATE       TIMESTAMP,
  STOCK      STRING,
  SENTIMENT  STRING,
  EMBEDDING  VECTOR(FLOAT, 768)
);


-- Pipe loads CSV files from stage into the landing table
CREATE OR REPLACE PIPE "STOCK_NEWS_PIPE" AUTO_INGEST = FALSE AS
  COPY INTO "STOCK_NEWS_RAW"
  FROM @"STOCK_NEWS_STAGE"
  FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);


-- Stream captures new rows arriving in the landing table
CREATE OR REPLACE STREAM "STOCK_NEWS_STREAM" ON TABLE "STOCK_NEWS_RAW";

-- Task processes new rows: classifies headline sentiment, embeds, and inserts into final table
CREATE OR REPLACE TASK "STOCK_NEWS_CLASSIFY_TASK"
  WAREHOUSE = DOD_WAREHOUSE
  // SCHEDULE  = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('STOCK_NEWS_STREAM')
AS
  INSERT INTO STOCK_NEWS_EVENT (HEADLINE, PUBLISHER, DATE, STOCK, SENTIMENT, EMBEDDING)
  SELECT
    HEADLINE,
    PUBLISHER,
    DATE,
    STOCK,
    AI_CLASSIFY(HEADLINE, ['POSITIVE', 'NEGATIVE']):labels[0]::STRING AS SENTIMENT,
    AI_EMBED('snowflake-arctic-embed-m-v1.5', HEADLINE) AS EMBEDDING
  FROM "STOCK_NEWS_STREAM";


-- Resume the task so it runs
ALTER TASK "STOCK_NEWS_CLASSIFY_TASK" RESUME;

SHOW TASKS LIKE 'STOCK_NEWS_CLASSIFY_TASK';


-- SHOW staged data
LIST @"STOCK_NEWS_STAGE";

ALTER PIPE "STOCK_NEWS_PIPE" REFRESH;

SELECT * FROM "STOCK_NEWS_RAW";
SELECT * FROM "STOCK_NEWS_STREAM";

-- Read from the table
SELECT * FROM "STOCK_NEWS_EVENT";
