USE ROLE "DOD_DEVELOPER";
USE DATABASE "DOD2026";
USE SCHEMA "PUBLIC";

-- Stock prices
CREATE TABLE IF NOT EXISTS "DAILY_STOCK_PRICES"
(
  "DATE" TIMESTAMP_TZ NOT NULL,
  "TICKER" VARCHAR(20) NOT NULL,
  "CLOSE_PRICE" NUMBER(12,4) NOT NULL
);


SELECT * FROM "DAILY_STOCK_PRICES";


-- Create a stage

CREATE STAGE "STOCK_DATA_STAGE";
LIST @"STOCK_DATA_STAGE";

-- Load data from stage

COPY INTO "DAILY_STOCK_PRICES"
FROM @"STOCK_DATA_STAGE"
FILES = ('snp_daily_dataset.csv')
FILE_FORMAT = (
    TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
);


-- Stock daily returns
CREATE OR REPLACE DYNAMIC TABLE "DYN_STOCKS_DAILY_RETURNS"
TARGET_LAG = DOWNSTREAM
WAREHOUSE = DOD_WAREHOUSE
AS
SELECT
    TICKER,
    DATE,
    CLOSE_PRICE,

    LAG(CLOSE_PRICE)
      OVER (
        PARTITION BY TICKER
        ORDER BY DATE
      ) AS PREVIOUS_CLOSE,

    CLOSE_PRICE /
        NULLIF(LAG(CLOSE_PRICE)
        OVER (
            PARTITION BY TICKER
            ORDER BY DATE
        ), 0) - 1 AS DAILY_RETURN
FROM "DAILY_STOCK_PRICES";


ALTER DYNAMIC TABLE "DYN_STOCKS_DAILY_RETURNS" REFRESH;

SELECT * FROM "DYN_STOCKS_DAILY_RETURNS";

SELECT "TICKER", "DATE", ROUND("DAILY_RETURN" * 100, 2) || '%' AS "DAILY_RETURN_PCT"  FROM "DYN_STOCKS_DAILY_RETURNS" WHERE "TICKER" = 'AAPL' ORDER BY "DATE" DESC;

-- Best trading days of a single stock (e.g. NVDA)
SELECT
    TICKER,
    DATE,
    CLOSE_PRICE,
    PREVIOUS_CLOSE,
    ROUND(DAILY_RETURN * 100, 2) || '%' AS DAILY_RETURN_PCT
FROM "DYN_STOCKS_DAILY_RETURNS"
WHERE DAILY_RETURN IS NOT NULL
AND "TICKER" = 'NVDA'
ORDER BY DAILY_RETURN DESC
LIMIT 3;


-- Best day for the market on average
SELECT
    DATE,
    ROUND(AVG(DAILY_RETURN) * 100, 2) || '%' AS AVG_DAILY_RETURN_PCT
FROM "DYN_STOCKS_DAILY_RETURNS"
WHERE DAILY_RETURN IS NOT NULL
GROUP BY DATE
ORDER BY AVG(DAILY_RETURN) DESC
LIMIT 100;


-- Cleanup
DROP TABLE "DAILY_STOCK_PRICES";
DROP DYNAMIC TABLE "DYN_STOCKS_DAILY_RETURNS";