USE ROLE "DOD_DEVELOPER";
USE DATABASE "DOD2026";
USE SCHEMA "PUBLIC";
USE WAREHOUSE "DOD_WAREHOUSE";

SHOW SCHEMAS;
SHOW TABLES;

CREATE TABLE IF NOT EXISTS "STOCK_NEWS"
(
    "ID" VARCHAR(36) NOT NULL,
    "TICKER" VARCHAR(20) NOT NULL,
    "TEXT" VARCHAR NOT NULL,
    "DATE" DATE NOT NULL,
    CONSTRAINT "PK_STOCK_NEWS" PRIMARY KEY ("ID")
);

-- Create a transient clone from schema (zerocopy / COW)
CREATE TRANSIENT SCHEMA IF NOT EXISTS "CUSTOM_CI_123" CLONE "PUBLIC";

USE SCHEMA "CUSTOM_CI_123";
SHOW TABLES;

SELECT * FROM "CUSTOM_CI_123"."DAILY_STOCK_PRICES" ORDER BY "TICKER";
-- Delete data in current schema 
DELETE FROM "CUSTOM_CI_123"."DAILY_STOCK_PRICES" WHERE "TICKER" = 'A';

-- Data is still present on public
SELECT * FROM "PUBLIC"."DAILY_STOCK_PRICES" ORDER BY "TICKER";

-- Drop temporary schema again
DROP SCHEMA "CUSTOM_CI_123";
