CREATE TABLE IF NOT EXISTS "STOCK_NEWS"
(
    "ID" VARCHAR(36) NOT NULL,
    "TICKER" VARCHAR(20) NOT NULL,
    "TEXT" VARCHAR NOT NULL,
    "DATE" DATE NOT NULL,
    CONSTRAINT "PK_STOCK_NEWS" PRIMARY KEY ("ID")
);